# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.14.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]

  - repo: https://github.com/asottile/pyupgrade
    rev: "v2.38.0"
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/ikamensh/flynt
    rev: "0.76"
    hooks:
      - id: flynt
        args: [--line-length, "120"]

  - repo: https://github.com/PyCQA/autoflake # configuration in pyproject.toml
    rev: "v1.5.3"
    hooks:
      - id: autoflake
        args: []

  # isort and black should be after other python hooks
  - repo: https://github.com/pycqa/isort # configuration in pyproject.toml
    rev: "5.12.0"
    hooks:
      - id: isort
        name: isort (python)

  # isort and black should be after other python hooks, black should be after isort
  - repo: https://github.com/psf/black # configuration in pyproject.toml
    rev: "22.6.0" # If you updated this, also update in pyproject.toml
    hooks:
      - id: black

  # this should be the last hook
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: trailing-whitespace # trims trailing whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline
      - id: check-yaml # checks syntax of yaml files
      - id: check-json # checks syntax of json files
        exclude: |
          (?x)^(
            \.vscode/.*\.json
          )$
      - id: check-added-large-files # prevent giant files from being committed
      - id: fix-encoding-pragma # removes "# -*- coding: utf-8 -*-" from python files (since we only support python 3)
        args: [--remove]
      - id: check-merge-conflict # check for files that contain merge conflict strings
