language: python

sudo: true

install:
  - sudo apt-get install clamav-daemon clamav-freshclam clamav-unofficial-sigs
  - sudo freshclam --verbose
  - sudo service clamav-daemon start
  - pip install tox

script: tox

matrix:
  fast_finish: true
  include:
    - env: TOXENV=py27-dj18
      python: 2.7
    - env: TOXENV=py34-dj18
      python: 3.4
    - env: TOXENV=py35-dj18
      python: 3.5
    - env: TOXENV=py27-dj111
      python: 2.7
    - env: TOXENV=py34-dj111
      python: 3.4
    - env: TOXENV=py35-dj111
      python: 3.5
    - env: TOXENV=py35-dj111
      python: 3.6
    - env: TOXENV=py310-dj111
      python: 3.10
